services:

  node:
    build: ./api
    restart: always
    ports:
      - "3000:3000"
    depends_on:      
      db:
        condition: service_started

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: portfolio